'use strict';
var assert=require('assert'),fs=require('fs');
var state=fs.readFileSync('state.js','utf8');
var script=fs.readFileSync('script.js','utf8');
var open=fs.readFileSync('js/sync/discovered-conference-open-service.js','utf8');
var orchestrator=fs.readFileSync('js/sync/automatic-sync-orchestrator.js','utf8');
assert.doesNotMatch(state,/function restoreSafeSingleCurrentConferenceSelection[\s\S]*?target\.currentConferenceId\s*=/);
assert.match(state,/capturePersistedCandidate\(persistedCandidate,selection\.source\)/);
assert.match(state,/appData\.currentConferenceId=null/);
assert.match(state,/preparePersistedAppData\(appData\)/);
assert.match(script,/function setCurrentConferenceById[\s\S]*?activationAuthorization\.canDisplay/);
assert.match(script,/function restoreBackup[\s\S]*?backup_authorization_unverified/);
assert.match(script,/function restoreArchive[\s\S]*?archive_authorization_unverified/);
assert.match(script,/function importSingleConferenceData[\s\S]*?import_authorization_unverified/);
assert.match(script,/function activatePersistedConferenceById[\s\S]*?activationAuthorization\.activate/);
assert.doesNotMatch(script,/currentConferenceRuntimeAccessRole===null\|\|/);
assert.match(script,/function canEditCurrentConferenceData[\s\S]*?authorization\.canEdit/);
assert.match(script,/reconcileStartup\([\s\S]*?validateAuthorization/);
assert.match(open,/validateAuthorization:validateAuthorization/);
assert.match(open,/publishCloudAuthorization/);
assert.match(open,/deactivateRuntimeAuthorization/);
assert.match(open,/conference_authorization_revoked/);
assert.match(orchestrator,/authorization\.canSync/);
console.log('conference activation boundary contract tests: passed');
