'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
var root=path.resolve(__dirname,'..');
var service=fs.readFileSync(path.join(root,'js/supabase/current-device-authorization-service.js'),'utf8');
var ui=fs.readFileSync(path.join(root,'js/sync/current-device-authorization-ui.js'),'utf8');
var repository=fs.readFileSync(path.join(root,'js/sync/device-authorization-operation-repository.js'),'utf8');
var index=fs.readFileSync(path.join(root,'index.html'),'utf8');
var worker=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
var ids={user:'11111111-1111-4111-8111-111111111111',device:'22222222-2222-4222-8222-222222222222',operation:'33333333-3333-4333-8333-333333333333'};
var calls=[],store={},requestAttempts=0;var element={innerHTML:''};
var sandbox={window:null,Promise:Promise,JSON:JSON,Object:Object,String:String,Array:Array,Date:Date,console:console,confirm:function(){return true;},localStorage:{getItem:function(k){return store[k]||null;},setItem:function(k,v){store[k]=v;}},crypto:{randomUUID:function(){return ids.operation;}},document:{getElementById:function(){return element;}},OrganizationAdministrationUtils:{isUuid:function(v){return /^[0-9a-f-]{36}$/i.test(v);}},SupabaseAuth:{initialize:function(){return Promise.resolve();},getSession:function(){return {user:{id:ids.user}};}},SupabaseDeviceIdentity:{getOrCreate:function(){return {id:ids.device,deviceName:'Work',platform:'Test'};}},SupabaseClientLayer:{getClient:function(){return {rpc:function(name,args){calls.push({name:name,args:args});if(name==='get_my_device_authorization')return Promise.resolve({data:{deviceAuthorizationStatus:'registered'},error:null});if(name==='get_my_device_aware_system_access')return Promise.resolve({data:{enforcementEnabled:false},error:null});if(name==='register_or_refresh_current_device')return Promise.resolve({data:{status:'registered'},error:null});requestAttempts++;return requestAttempts===1?Promise.reject(new Error('network')):Promise.resolve({data:{status:'pending'},error:null});}};}}};sandbox.window=sandbox;
vm.runInNewContext(repository,sandbox);vm.runInNewContext(service,sandbox);vm.runInNewContext(ui,sandbox);
(async function(){
  await sandbox.CurrentDeviceAuthorizationUI.initialize();
  assert.deepStrictEqual(calls.map(function(c){return c.name;}),['get_my_device_authorization','get_my_device_aware_system_access']);
  assert.doesNotMatch(service+ui,/setInterval|setTimeout/,'Gate 2 status must not poll');
  await sandbox.CurrentDeviceAuthorizationUI.registerDevice();
  assert.strictEqual(calls.filter(function(c){return c.name==='register_or_refresh_current_device';}).length,1);
  var ambiguous=await sandbox.CurrentDeviceAuthorizationUI.requestAuthorization();assert.strictEqual(ambiguous.status,'ambiguous');
  await sandbox.CurrentDeviceAuthorizationUI.requestAuthorization();
  var requests=calls.filter(function(c){return c.name==='request_current_device_authorization';});
  assert.strictEqual(requests.length,2);assert.strictEqual(requests[0].args.p_device_id,ids.device);
  assert.strictEqual(requests[0].args.p_operation_id,ids.operation);assert.strictEqual(requests[1].args.p_operation_id,ids.operation);
  ['حالة اعتماد هذا الجهاز','غير مسجل','مسجل','بانتظار الموافقة','معتمد','مرفوض أو ملغى','تعذر التحقق','تحديث الحالة','لن يتم اعتماد الجهاز تلقائيًا.'].forEach(function(text){assert.ok(ui.includes(text),text);});
  ['js/sync/device-authorization-operation-repository.js','js/supabase/current-device-authorization-service.js','js/supabase/device-authorization-administration-service.js','js/sync/current-device-authorization-ui.js','js/sync/device-authorization-administration-ui.js'].forEach(function(file){assert.ok(index.includes(file));assert.ok(worker.includes('./'+file));});
  assert.ok(worker.includes("CACHE_REVISION = 'conference-runtime-stability-v1'"));
  assert.ok(ui.includes('طلب اعتماد الجهاز مرة أخرى'));
  assert.ok(ui.includes("state.status==='revoked'&&state.accountStatus==='approved'"));
  console.log('current-device authorization Gate 2 tests: passed (explicit refresh/register/request; no polling)');
})().catch(function(error){console.error(error);process.exitCode=1;});
