'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');var root=path.resolve(__dirname,'..');
var service=fs.readFileSync(path.join(root,'js/supabase/device-authorization-administration-service.js'),'utf8');
var ui=fs.readFileSync(path.join(root,'js/sync/device-authorization-administration-ui.js'),'utf8');
var repository=fs.readFileSync(path.join(root,'js/sync/device-authorization-operation-repository.js'),'utf8');
var index=fs.readFileSync(path.join(root,'index.html'),'utf8');var worker=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
var mappings={list_member_device_authorizations:['p_actor_device_id','p_organization_id','p_target_user_id'],approve_member_device:['p_actor_device_id','p_organization_id','p_target_user_id','p_device_id','p_operation_id'],reject_member_pending_device:['p_actor_device_id','p_organization_id','p_target_user_id','p_device_id','p_operation_id'],revoke_member_device:['p_actor_device_id','p_organization_id','p_target_user_id','p_device_id','p_operation_id'],replace_member_active_device:['p_actor_device_id','p_organization_id','p_target_user_id','p_active_device_id','p_replacement_device_id','p_operation_id']};
Object.keys(mappings).forEach(function(name){assert.ok(service.includes("'"+name+"'"),name);mappings[name].forEach(function(arg){assert.ok(service.includes(arg),name+' '+arg);});});
assert.doesNotMatch(service+ui,/\.from\s*\(|\.channel\s*\(|postgres_changes|P03CStaged|device_guarded_/);
assert.doesNotMatch(service+ui,/setInterval/);
assert.match(service,/return listMemberDevices\(\{organizationId:organizationId,targetUserId:targetUserId\}/,'terminal mutation refresh must target the affected member only');
assert.doesNotMatch(service,/listMyOrganizations|listMembers/,'mutation service must not refresh organization directories');
assert.match(ui,/اختر الجهاز البديل/);assert.match(ui,/replaceFrom/);assert.match(service,/replacement===deviceId/);
['إدارة أجهزة الأعضاء','تحديث الأجهزة','اعتماد الجهاز','رفض الطلب','إلغاء اعتماد الجهاز','استبدال الجهاز المعتمد','نتيجة العملية غير مؤكدة وتتطلب إعادة تحقق.'].forEach(function(text){assert.ok(ui.includes(text),text);});
['كل الحالات','بانتظار الموافقة','معتمد','مرفوض أو ملغى','مسجل'].forEach(function(text){assert.ok(ui.includes(text),text);});
assert.match(ui,/setStatusFilter/);
assert.match(service,/ownerPendingRequestsCount/);
assert.match(repository,/actorUserId===input\.actorUserId/);assert.match(repository,/operationId:operationId,state:'pending'/);assert.match(repository,/markUnknown/);
assert.ok(index.indexOf('device-authorization-operation-repository.js')<index.indexOf('current-device-authorization-service.js'));
assert.ok(index.indexOf('current-device-authorization-service.js')<index.indexOf('device-authorization-administration-service.js'));
assert.ok(index.indexOf('device-authorization-administration-service.js')<index.indexOf('current-device-authorization-ui.js'));
assert.ok(index.indexOf('current-device-authorization-ui.js')<index.indexOf('device-authorization-administration-ui.js'));
assert.doesNotMatch(index+worker,/js\/staged\/device-guarded|P03CStaged/);
console.log('device administration Gate 2 tests: passed (5 exact RPCs; explicit replacement; affected-member refresh only)');

var stored={},sandbox={window:null,Promise:Promise,JSON:JSON,Object:Object,Date:Date,localStorage:{getItem:function(key){return stored[key]||null;},setItem:function(key,value){stored[key]=value;}}};sandbox.window=sandbox;vm.runInNewContext(repository,sandbox);
(async function(){var repo=sandbox.DeviceAuthorizationOperationRepository,actorA='actor-a',actorB='actor-b',operation='operation-a';
  var original={actorUserId:actorA,intentKey:'approve|org|user|device',action:'approve',organizationId:'org',targetUserId:'user',deviceId:'device',replacementDeviceId:null};
  await repo.prepare(original,operation);await repo.markUnknown(actorA,operation);
  var immutable=await repo.prepare(Object.assign({},original,{deviceId:'changed'}),'different-operation');
  assert.strictEqual(immutable.data.operationId,operation);assert.strictEqual(immutable.data.deviceId,'device');assert.strictEqual(immutable.data.state,'unknown');
  assert.strictEqual((await repo.list(actorB)).data.operations.length,0);assert.strictEqual((await repo.get(actorB,operation)).status,'not_found');assert.strictEqual((await repo.remove(actorB,operation)).status,'not_found');
  assert.strictEqual((await repo.list(actorA)).data.operations.length,1);assert.strictEqual((await repo.get(actorA,operation)).data.state,'unknown');
  console.log('device authorization operation repository tests: passed (immutable intent; actor-isolated unresolved retention)');
})().catch(function(error){console.error(error);process.exitCode=1;});
