'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path');
var root=path.resolve(__dirname,'..');
var migration=fs.readFileSync(path.join(root,'supabase/migrations/20260805_5_4_4_multi_device_authorization.sql'),'utf8');
var ui=fs.readFileSync(path.join(root,'js/sync/device-authorization-administration-ui.js'),'utf8');
var gate=fs.readFileSync(path.join(root,'js/sync/device-reauthorization-flow.js'),'utf8');
var state=fs.readFileSync(path.join(root,'state.js'),'utf8');
var index=fs.readFileSync(path.join(root,'index.html'),'utf8');
var worker=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
assert.match(migration,/drop index if exists public\.user_device_authorizations_one_approved_per_user_idx/i);
assert.match(migration,/create index if not exists user_device_authorizations_approved_user_idx[\s\S]*authorization_status = 'approved'/i);
var approve=migration.match(/create or replace function public\.approve_member_device[\s\S]*?\n\$\$;/i)[0];
assert.match(approve,/authorization_status<>'pending'/i);
assert.match(approve,/set authorization_status='approved'/i);
assert.doesNotMatch(approve,/exists\s*\(select 1 from public\.user_device_authorizations[\s\S]*authorization_status='approved'/i);
assert.doesNotMatch(approve,/replace_member_active_device|authorization_status='revoked'/i);
var revoke=migration.match(/create or replace function public\.revoke_member_device[\s\S]*?\n\$\$;/i)[0];
assert.match(revoke,/count\(\*\)[\s\S]*authorization_status='approved'[\s\S]*<=1/i);
assert.strictEqual((revoke.match(/set authorization_status='revoked'/gi)||[]).length,1);
var replace=migration.match(/create or replace function public\.replace_member_active_device[\s\S]*?\n\$\$;/i)[0];
assert.strictEqual((replace.match(/set authorization_status='revoked'/gi)||[]).length,1);
assert.strictEqual((replace.match(/set authorization_status='approved'/gi)||[]).length,1);
assert.doesNotMatch(replace,/count\(\*\)[\s\S]*authorization_status='approved'[\s\S]*<>1/i);
assert.doesNotMatch(ui,/action==='approve'&&approved\.length===1|effectiveAction='replace'/);
assert.match(ui,/replaceFrom/);
assert.match(gate,/status==='approved'/);
assert.doesNotMatch(gate,/isSoleApprovedDevice|approvedDeviceCount|count/);
assert.doesNotMatch(migration+ui,/SyncQueue|revision|ConferenceLinkStore|AutomaticSync/);
assert.match(state,/DeviceReauthorizationFlow\.waitUntilApproved/);
['js/sync/device-authorization-administration-ui.js?rev=multi-device-authorization-v1'].forEach(function(asset){assert.ok(index.includes(asset),asset);assert.ok(worker.includes('./'+asset),asset);});
console.log('multi-device authorization contract tests: passed');
