const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('js/sync/organization-template-sync.js','utf8');
function runtime(remoteRows,organizations){
  const records=[],rpcCalls=[],data={houseTemplates:[],templates:[],conferences:[],currentConferenceId:null};
  const window={JSON,Promise,Date,crypto:{randomUUID:(()=>{let n=0;return()=>`00000000-0000-4000-8000-${String(++n).padStart(12,'0')}`;})()},appData:data,localStorage:{setItem(){}},SK:'x'};
  window.SupabaseAuth={getState:()=>({authenticated:true,user:{id:'10000000-0000-4000-8000-000000000001'}})};
  window.SupabaseDeviceIdentity={getOrCreate:()=>({id:'20000000-0000-4000-8000-000000000001'})};
  window.SupabaseClientLayer={getClient:()=>({rpc:(name,args)=>{rpcCalls.push({name,args});if(name==='list_organization_templates')return Promise.resolve({data:{status:'success',templates:remoteRows||[]}});return Promise.resolve({data:{status:args.p_action==='delete'?'deleted':args.p_base_revision?'updated':'created',revision:args.p_base_revision+1}});}})};
  window.OrganizationManagementService={list:()=>Promise.resolve({ok:true,data:{organizations:organizations||[{organizationId:'30000000-0000-4000-8000-000000000001',status:'active'}]}})};
  window.AppIndexedDB={stores:{organizationTemplateOperations:'ops'},getAllRecords:()=>Promise.resolve(records.slice()),putRecord:(s,v)=>{let i=records.findIndex(x=>x.operationId===v.operationId);if(i<0)records.push(v);else records[i]=v;return Promise.resolve();},deleteRecord:(s,id)=>{let i=records.findIndex(x=>x.operationId===id);if(i>=0)records.splice(i,1);return Promise.resolve();}};
  window.StorageRepository={getAppSnapshot:()=>Promise.resolve({data:window.appData}),saveAppSnapshot:value=>{window.appData=value;return Promise.resolve({ok:true});}};
  vm.runInNewContext(source,{window,console});return {window,records,rpcCalls};
}
(async()=>{
  let r=runtime([]);r.window.appData.houseTemplates=[{id:'h1',name:'House',floors:[]}];let first=await r.window.OrganizationTemplateSync.refresh();assert.equal(first.ok,true);assert.equal(r.window.appData.houseTemplates.length,1,'legacy adoption must not duplicate');assert.equal(r.rpcCalls.filter(x=>x.name==='apply_organization_template_operation').length,1);assert.equal(r.records.length,0);
  r=runtime([{organizationId:'30000000-0000-4000-8000-000000000001',templateType:'house',templateId:'h2',payload:{id:'h2',name:'Cloud',floors:[]},revision:4,deletedAt:null}]);await r.window.OrganizationTemplateSync.refresh();assert.equal(r.window.appData.houseTemplates[0].name,'Cloud');assert.equal(r.window.appData.houseTemplates[0].cloudRevision,4);
  r.window.appData.houseTemplates[0].name='Edited';await r.window.OrganizationTemplateSync.captureLocalSave(r.window.appData);await new Promise(resolve=>setTimeout(resolve,0));assert.equal(r.rpcCalls.some(x=>x.name==='apply_organization_template_operation'&&x.args.p_base_revision===4),true);
  r=runtime([]);await r.window.OrganizationTemplateSync.refresh();let release;r.window.SupabaseClientLayer.getClient=()=>({rpc:()=>new Promise(resolve=>{release=resolve;})});r.window.appData.houseTemplates=[{id:'offline-new',name:'Draft',floors:[],organizationId:'30000000-0000-4000-8000-000000000001'}];await r.window.OrganizationTemplateSync.captureLocalSave(r.window.appData);assert.equal(r.records.length,1);r.window.appData.houseTemplates=[];await r.window.OrganizationTemplateSync.captureLocalSave(r.window.appData);assert.equal(r.records.length,0,'offline create then delete must cancel a not-sent create');release({data:{status:'created',revision:1}});await new Promise(resolve=>setTimeout(resolve,0));assert.equal(r.records.length,1,'an in-flight create requires a compensating delete');assert.equal(r.records[0].action,'delete');assert.equal(r.records[0].baseRevision,1);
  r=runtime([{organizationId:'30000000-0000-4000-8000-000000000001',templateType:'house',templateId:'gone',payload:null,revision:3,deletedAt:'2026-08-12T00:00:00Z'}]);r.window.appData.houseTemplates=[{id:'gone',name:'Stale',floors:[],organizationId:'30000000-0000-4000-8000-000000000001'}];await r.window.OrganizationTemplateSync.refresh();assert.equal(r.window.appData.houseTemplates.length,0,'a tombstone must remove stale local materialization');
  r=runtime([],[{organizationId:'30000000-0000-4000-8000-000000000001',status:'active'},{organizationId:'30000000-0000-4000-8000-000000000002',status:'active'}]);r.window.appData.houseTemplates=[{id:'legacy',name:'Unscoped',floors:[]}];await r.window.OrganizationTemplateSync.refresh();assert.equal(r.window.appData.houseTemplates.length,1);assert.equal(r.window.appData.houseTemplates[0].organizationId,undefined,'multi-organization legacy data must remain unscoped');assert.equal(r.rpcCalls.filter(x=>x.name==='apply_organization_template_operation').length,0);
  console.log('organization-template-sync: PASS');
})().catch(error=>{console.error(error);process.exit(1);});
