'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const source=fs.readFileSync(path.resolve(__dirname,'../js/sync/organization-management-ui.js'),'utf8'),root={style:{display:'none'},innerHTML:''},header={style:{}},button={classList:{add(){},remove(){}}};
const organizations=Array.from({length:10},(_,index)=>({organizationId:`00000000-0000-4000-8000-${String(index+1).padStart(12,'0')}`,displayName:'Organization '+(index+1),description:index?'Description':'',status:index===9?'archived':'active',createdAt:'2026-08-10',role:'organization_owner',ownerName:'Owner',conferenceCount:index,memberCount:index+1,deviceCount:index+2,capabilities:{canOpen:true,canManageMembers:true,canEdit:true,canArchive:index!==9,canDelete:false}}));
let rows=organizations.slice(),created=0;
const service={list:()=>Promise.resolve({ok:true,data:{canCreate:true,organizations:rows}}),create:input=>{created++;rows=rows.concat([Object.assign({},organizations[0],{organizationId:input.organizationId,displayName:input.name})]);return Promise.resolve({ok:true,status:'created',data:{overview:{canCreate:true,organizations:rows}}});},update:()=>Promise.resolve({ok:true,status:'updated',data:{overview:{canCreate:true,organizations:rows}}}),archive:()=>Promise.resolve({ok:true,status:'archived',data:{overview:{canCreate:true,organizations:rows}}})};
const document={getElementById:id=>id==='organizationManagementScreen'?root:id==='globalConferenceHeader'?header:id==='organizationManagementTabButton'?button:null,querySelectorAll:()=>[]};
const sandbox={window:{document,OrganizationManagementService:service,StartupAccessGate:{isAllowed:()=>true},setApplicationMode:()=>{},crypto:{randomUUID:()=> '99999999-9999-4999-8999-999999999999'},confirm:()=>true},Promise};vm.runInNewContext(source,sandbox);const ui=sandbox.window.OrganizationManagementUI;
(async()=>{await ui.open();assert(root.innerHTML.includes('إدارة المؤسسات'));assert(root.innerHTML.includes('+ مؤسسة جديدة'));assert.strictEqual((root.innerHTML.match(/class="organization-card"/g)||[]).length,10);ui.select(organizations[0].organizationId,'manage');assert(root.innerHTML.includes('تعديل الاسم والوصف'));assert(root.innerHTML.includes('أرشفة المؤسسة'));rows=[];await ui.refresh();assert(root.innerHTML.includes('لا توجد مؤسسات'));rows=organizations.slice();await ui.refresh();ui.create();assert(root.innerHTML.includes('organization_dialog_name'));assert.doesNotMatch(source,/\.from\s*\(|\.insert\s*\(|\.update\s*\(|\.delete\s*\(/);assert.strictEqual(created,0);console.log('organization management UI tests: passed');})().catch(error=>{console.error(error);process.exitCode=1;});
