'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const migration=fs.readFileSync(path.join(root,'supabase/migrations/20260827_6_20_0_platform_privileged_device_administration.sql'),'utf8');
const edge=fs.readFileSync(path.join(root,'supabase/functions/platform-device-authorization/index.ts'),'utf8');
const service=fs.readFileSync(path.join(root,'js/supabase/device-authorization-administration-service.js'),'utf8');
const organization=fs.readFileSync(path.join(root,'supabase/migrations/20260802_5_4_2_device_authorization_administration.sql'),'utf8');
const protectedFiles=['20260826_6_17_0_conference_authorization_chain_hardening.sql','20260826_6_18_0_conference_lifecycle_hardening.sql','20260826_6_19_0_snapshot_sync_account_authorization_hardening.sql'];
['issue_system_owner_credential_bootstrap_authorization','begin_system_owner_device_possession_challenge','complete_system_owner_credential_enrollment','complete_system_owner_pending_device_listing','list_system_owner_pending_device_authorizations','complete_system_owner_pending_device_operation','get_system_owner_device_operation_result'].forEach(name=>assert.ok(migration.includes('public.'+name+'('),name));
assert.doesNotMatch(migration,/organization_members|conference_members|public\.conferences/i);
assert.match(migration,/authorization_status='pending'[\s\S]*revoked_at is null[\s\S]*account_status='approved'/i);
assert.match(migration,/challenge_hash=p_challenge_hash/g);
assert.match(migration,/grant execute[\s\S]*to service_role/i);
assert.doesNotMatch(migration,/grant execute[\s\S]*to authenticated/i);
assert.match(migration,/auth\.jwt\(\)->>'role'[^\n]*'service_role'/i);
assert.match(edge,/auth\.getUser\(\)/);
assert.match(edge,/verifyRegistrationResponse/);
assert.match(edge,/verifyAuthenticationResponse/);
assert.match(edge,/requireUserVerification:\s*true/);
assert.match(edge,/WEBAUTHN_EXPECTED_ORIGIN/);
assert.match(edge,/WEBAUTHN_RP_ID/);
assert.match(edge,/SUPABASE_SERVICE_ROLE_KEY/);
assert.doesNotMatch(service,/SUPABASE_SERVICE_ROLE_KEY|service_role/);
assert.match(service,/navigator\.credentials\.get/);
assert.match(service,/navigator\.credentials\.create/);
assert.match(service,/listSystemOwnerPendingDevices/);
assert.match(service,/approveSystemOwnerPendingDevice/);
['require_device_authorization_manager','list_member_device_authorizations','approve_member_device','reject_member_pending_device','revoke_member_device','replace_member_active_device'].forEach(name=>assert.ok(organization.includes('public.'+name+'(')));
protectedFiles.forEach(name=>assert.ok(fs.existsSync(path.join(root,'supabase/migrations',name))));
console.log('platform privileged device administration contracts: passed');
