'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const sql=fs.readFileSync(path.resolve(__dirname,'../supabase/migrations/20260827_6_20_0_platform_privileged_device_administration.sql'),'utf8');
const completion=sql.slice(sql.indexOf('create or replace function public.complete_system_owner_pending_device_operation'),sql.indexOf('create or replace function public.get_system_owner_device_operation_result'));
['pg_advisory_xact_lock','for update','require_system_owner_webauthn_actor','challenge_hash=p_challenge_hash','expires_at<=statement_timestamp()','p_new_sign_count<credential.sign_count','device_possession_challenge_consumers','system_owner_device_authorization_operations','privileged_device_authorization_audit_log','consumed_at=statement_timestamp()'].forEach(contract=>assert.ok(completion.includes(contract),contract));
assert.ok(completion.indexOf('device_possession_challenge_consumers')<completion.indexOf("set consumed_at=statement_timestamp()"));
assert.match(sql,/system-owner-device-operation:/);
assert.match(sql,/PLATFORM_DEVICE_OPERATION_MISMATCH/);
assert.match(sql,/stored_result/);
assert.match(sql,/authorization_status='pending'[\s\S]*account_status='approved'[\s\S]*for update of authorization/i);
assert.match(sql,/challenge\.verified_at is not null[\s\S]*challenge\.consumed_at is not null[\s\S]*challenge\.failed_at is not null/);
assert.match(sql,/APPROVED_SYSTEM_OWNER_REQUIRED|APPROVED_SYSTEM_OWNER_DEVICE_REQUIRED/);
assert.match(sql,/APPROVED_ACTOR_DEVICE_REQUIRED/);
assert.match(sql,/ACTIVE_PLATFORM_CREDENTIAL_REQUIRED/);
assert.match(sql,/fail_system_owner_device_possession_challenge/);
assert.match(sql,/failed_at=statement_timestamp\(\)[\s\S]*failure_code=/);
console.log('platform privileged device transaction contracts: passed');
