'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const test=require('node:test');
const file='supabase/migrations/20260907160000_production_foundation_reconciliation.sql';
const sql=fs.readFileSync(file,'utf8');
const normalized=sql.replace(/--[^\n]*/g,'');
function before(a,b){assert.ok(sql.indexOf(a)>=0,a);assert.ok(sql.indexOf(b)>sql.indexOf(a),b+' must follow '+a);}
function fixtureProjection(accounts,owners,devices){return {profiles:accounts.map(row=>({userId:row.id,status:row.status})),owners:owners.filter(id=>accounts.some(row=>row.id===id&&row.status==='approved')).map(userId=>({userId,role:'platform_owner'})),devices:devices.map(row=>({userId:row.userId,deviceId:row.deviceId,legacyStatus:row.status,state:row.status==='approved'?'requires_cryptographic_handoff':row.status==='revoked'?'revoked':'pending_reenrollment',usable:false}))};}
function fixtureProfiles(authUsers,accounts){const profiles=new Map(authUsers.map(id=>[id,{userId:id,status:'pending'}]));for(const account of accounts)profiles.set(account.id,{userId:account.id,status:account.status});return Array.from(profiles.values());}
function reconcileProfiles(authUsers,legacyAccounts,preexistingProfiles=[]){
  const profiles=new Map(preexistingProfiles.map(row=>[row.userId,{...row}]));
  for(const account of legacyAccounts){const existing=profiles.get(account.id);if(existing&&existing.status!==account.status)throw new Error('PLATFORM_PROFILE_LEGACY_CONFLICT');}
  for(const id of authUsers)if(!profiles.has(id))profiles.set(id,{userId:id,status:'pending'});
  for(const account of legacyAccounts)profiles.set(account.id,{userId:account.id,status:account.status});
  return Array.from(profiles.values());
}

test('1 explicit Production reconciliation has no Development target dependency',()=>{assert.doesNotMatch(sql,/gppwltrifgfxrkzvvxoe|development_preview/i);});
test('2 stable Development recovery chain is absent',()=>assert.doesNotMatch(sql,/stable[_ -]?development|device_recovery|recovery_state|expired_challenge/i));
test('3 no owner identity is hardcoded',()=>{assert.doesNotMatch(sql,/ramyawny37@yahoo\.com/i);assert.doesNotMatch(sql,/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);});
test('4 auth users are validation-only and never mutated',()=>{assert.match(sql,/left join auth\.users/);assert.doesNotMatch(normalized,/(?:insert into|update|delete from)\s+auth\.users/i);});
test('5 legacy authority is never deleted reset or truncated',()=>assert.doesNotMatch(normalized,/truncate|delete from public\.(?:system_user_access|system_user_roles)|update public\.(?:system_user_access|system_user_roles)/i));
test('6 legacy account projects to same-user Platform profile',()=>assert.match(sql,/insert into platform\.profiles\([\s\S]*select access\.user_id,access\.account_status[\s\S]*from public\.system_user_access access/i));
test('7 all three canonical account states pass through unchanged',()=>{for(const status of ['approved','pending','blocked'])assert.match(sql,new RegExp("'"+status+"'"));assert.match(sql,/select access\.user_id,access\.account_status/);assert.match(sql,/account_status=excluded\.account_status/);});
test('8 owner projection is one-way from system_owner to platform_owner',()=>{before("legacy.role='system_owner'","insert into platform.user_roles");assert.match(sql,/role\.code='platform_owner'/);assert.doesNotMatch(sql,/insert into public\.system_user_roles|update public\.system_user_roles/i);});
test('9 independent Platform owner authority fails closed',()=>assert.match(sql,/INDEPENDENT_PLATFORM_OWNER_CONTRADICTION/));
test('10 duplicate active owner assignment is prevented',()=>assert.match(sql,/not exists\(select 1 from platform\.user_roles assignment[\s\S]*assignment\.revoked_at is null\)/));
test('11 first-owner bootstrap is never executed',()=>assert.doesNotMatch(normalized,/complete_first_system_bootstrap\s*\(|first_platform_owner_bootstrap\s*\(/i));
test('12 device bridge creates no Platform device or authorization credential',()=>{assert.doesNotMatch(normalized,/insert into platform\.devices|insert into platform\.user_device_authorizations/);assert.match(sql,/create table platform_private\.legacy_device_reconciliation_boundaries/);assert.doesNotMatch(sql,/create table platform\.legacy_device_reconciliation_boundaries/);assert.match(sql,/usable_platform_credential boolean not null default false check\(usable_platform_credential=false\)/);});
test('13 approved legacy device is cordoned for cryptographic handoff',()=>assert.match(sql,/when 'approved' then 'requires_cryptographic_handoff'/));
test('14 pending and registered devices remain non-approved',()=>assert.match(sql,/when 'revoked' then 'revoked' else 'pending_reenrollment'/));
test('15 revoked device remains revoked',()=>assert.match(sql,/legacy_authorization_status='revoked' and reconciliation_state='revoked'/));
test('16 no device secret or hash is fabricated',()=>assert.doesNotMatch(sql,/secret_hash|device_secret|digest\s*\(|gen_random_bytes|random\s*\(/i));
test('17 actor-device override path is absent',()=>assert.doesNotMatch(sql,/p_actor_device_id|p_device_id|actor_device_override/i));
test('18 malformed and conflicting device state fails closed',()=>{assert.match(sql,/PRODUCTION_LEGACY_DEVICE_SOURCE_INVALID/);assert.match(sql,/LEGACY_PLATFORM_DEVICE_IDENTITY_CONFLICT/);});
test('19 Conference and Organization data are untouched',()=>assert.doesNotMatch(normalized,/(?:insert into|update|delete from|alter table)\s+(?:public\.)?(?:conferences|organizations|organization_members)/i));
test('20 Warehouse has no Organization dependency',()=>assert.doesNotMatch(sql,/warehouse|organization/i));
test('21 inventory authority is absent',()=>assert.doesNotMatch(sql,/inventory\./i));
test('22 account projection is compatible with ongoing reconciliation',()=>{const later=fs.readFileSync('supabase/migrations/20260906120000_system_access_platform_profile_reconciliation.sql','utf8');for(const field of ['account_status','approved_at','approved_by','blocked_at','blocked_by']){assert.match(sql,new RegExp(field));assert.match(later,new RegExp(field));}});
test('23 owner projection metadata matches ongoing one-way bridge',()=>{const later=fs.readFileSync('supabase/migrations/20260907120000_system_owner_platform_owner_reconciliation.sql','utf8');for(const value of ['authoritySource','system_owner','compatibilityProjection']){assert.match(sql,new RegExp(value));assert.match(later,new RegExp(value));}});
test('24 Development-only recovery migrations remain separate files',()=>{assert.ok(fs.existsSync('supabase/migrations/20260831050000_one_time_stable_development_device_recovery.sql'));assert.doesNotMatch(sql,/one_time_stable_development_device_recovery/);});
test('25 migration history is not fabricated',()=>assert.doesNotMatch(sql,/schema_migrations|migration_history/i));
test('26 source and pre-existing contradiction guards precede identity seeding and projection',()=>{const identitySeed='insert into platform.profiles(user_id,display_name)';const stateProjection='insert into platform.profiles(\n  user_id,account_status';before('PRODUCTION_ACCOUNT_SOURCE_INVALID','PLATFORM_PROFILE_LEGACY_CONFLICT');before('PLATFORM_PROFILE_LEGACY_CONFLICT',identitySeed);before(identitySeed,stateProjection);before('INDEPENDENT_PLATFORM_OWNER_CONTRADICTION','insert into platform.user_roles');});
test('27 migration is forward-only and transaction bounded',()=>{assert.match(sql,/^--[\s\S]*begin;/i);assert.match(sql,/commit;\s*$/i);assert.doesNotMatch(normalized,/\bdrop\b|\btruncate\b/i);});
test('28 established Production fixture projects exact identities without usable devices',()=>{const accounts=['owner','member-a','member-b'].map(id=>({id,status:'approved'}));const devices=[...Array(9)].map((_,i)=>({userId:i<3?'owner':'member-a',deviceId:'approved-'+i,status:'approved'})).concat([{userId:'member-b',deviceId:'pending',status:'pending'},{userId:'member-b',deviceId:'revoked',status:'revoked'}]);const result=fixtureProjection(accounts,['owner'],devices);assert.equal(result.profiles.length,3);assert.equal(result.profiles.filter(row=>row.status==='approved').length,3);assert.deepEqual(result.owners,[{userId:'owner',role:'platform_owner'}]);assert.equal(result.devices.filter(row=>row.state==='requires_cryptographic_handoff').length,9);assert.equal(result.devices.filter(row=>row.state==='pending_reenrollment').length,1);assert.equal(result.devices.filter(row=>row.state==='revoked').length,1);assert.equal(result.devices.some(row=>row.usable),false);});
test('29 account-state fixture never promotes pending or blocked',()=>{const result=fixtureProjection([{id:'a',status:'approved'},{id:'p',status:'pending'},{id:'b',status:'blocked'}],[],[]);assert.deepEqual(result.profiles.map(row=>row.status),['approved','pending','blocked']);});
test('30 fixture retains Conference and Organization baseline outside projection',()=>{const baseline={organizations:1,organizationMembers:3,conferences:1,nullOrganizationConferences:0};fixtureProjection([{id:'a',status:'approved'}],[],[]);assert.deepEqual(baseline,{organizations:1,organizationMembers:3,conferences:1,nullOrganizationConferences:0});});
test('31 private device ledger is inaccessible to API and service roles',()=>assert.match(sql,/revoke all on platform_private\.legacy_device_reconciliation_boundaries from public,anon,authenticated,service_role/));
test('32 auth identities are established before legacy actor foreign keys are copied',()=>{before('insert into platform.profiles(user_id,display_name)','insert into platform.profiles(\n  user_id,account_status');assert.match(sql,/select users\.id[\s\S]*from auth\.users users[\s\S]*on conflict\(user_id\) do nothing/);});
test('33 approved_by identity outside access remains pending until canonical projection',()=>{const profiles=fixtureProfiles(['account','external-approver'],[{id:'account',status:'approved',approvedBy:'external-approver'}]);assert.deepEqual(profiles,[{userId:'account',status:'approved'},{userId:'external-approver',status:'pending'}]);});
test('34 blocked_by identity outside access remains pending until canonical projection',()=>{const profiles=fixtureProfiles(['account','external-blocker'],[{id:'account',status:'blocked',blockedBy:'external-blocker'}]);assert.deepEqual(profiles,[{userId:'account',status:'blocked'},{userId:'external-blocker',status:'pending'}]);});
test('35 identity seeding never grants approval or authority',()=>{const identityBlock=sql.slice(sql.indexOf('insert into platform.profiles(user_id,display_name)'),sql.indexOf('insert into platform.profiles(\n  user_id,account_status'));assert.doesNotMatch(identityBlock,/account_status|platform\.user_roles|permission/i);});
test('36 fresh approved legacy account passes and becomes approved',()=>assert.deepEqual(reconcileProfiles(['approved-user'],[{id:'approved-user',status:'approved'}]),[{userId:'approved-user',status:'approved'}]));
test('37 fresh pending legacy account passes and remains pending',()=>assert.deepEqual(reconcileProfiles(['pending-user'],[{id:'pending-user',status:'pending'}]),[{userId:'pending-user',status:'pending'}]));
test('38 matching pre-existing approved Platform profile passes',()=>assert.deepEqual(reconcileProfiles(['approved-user'],[{id:'approved-user',status:'approved'}],[{userId:'approved-user',status:'approved'}]),[{userId:'approved-user',status:'approved'}]));
test('39 genuine pre-existing pending versus legacy approved contradiction fails closed',()=>assert.throws(()=>reconcileProfiles(['approved-user'],[{id:'approved-user',status:'approved'}],[{userId:'approved-user',status:'pending'}]),/PLATFORM_PROFILE_LEGACY_CONFLICT/));
test('40 actor FK identities are seeded pending after conflict guard and before projection',()=>{const result=reconcileProfiles(['account','external-approver','external-blocker'],[{id:'account',status:'approved',approvedBy:'external-approver',blockedBy:'external-blocker'}]);assert.deepEqual(result,[{userId:'account',status:'approved'},{userId:'external-approver',status:'pending'},{userId:'external-blocker',status:'pending'}]);before('PLATFORM_PROFILE_LEGACY_CONFLICT','insert into platform.profiles(user_id,display_name)');before('insert into platform.profiles(user_id,display_name)','insert into platform.profiles(\n  user_id,account_status');});
test('41 exact owner projection and unprojected device boundary remain unchanged',()=>{const result=fixtureProjection([{id:'owner',status:'approved'}],['owner'],[{userId:'owner',deviceId:'legacy-device',status:'approved'}]);assert.deepEqual(result.owners,[{userId:'owner',role:'platform_owner'}]);assert.deepEqual(result.devices,[{userId:'owner',deviceId:'legacy-device',legacyStatus:'approved',state:'requires_cryptographic_handoff',usable:false}]);assert.doesNotMatch(normalized,/insert into platform\.devices|insert into platform\.user_device_authorizations/);});
test('42 reserved authorization relation alias is absent from executable SQL',()=>{assert.doesNotMatch(normalized,/\b(?:from|join)\s+[^;\n]+\s+(?:as\s+)?authorization\b/i);assert.doesNotMatch(normalized,/\bauthorization\s*\./i);});
