'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path');
var root=path.resolve(__dirname,'..');
var migrationPath=path.join(root,'supabase/migrations/20260824_6_16_0_webauthn_privileged_device_security_foundation.sql');
var migration=fs.readFileSync(migrationPath,'utf8');
var verification=fs.readFileSync(path.join(root,'supabase/webauthn-privileged-device-security-foundation-readonly-verification.sql'),'utf8');
var organizationMigration=fs.readFileSync(path.join(root,'supabase/migrations/20260802_5_4_2_device_authorization_administration.sql'),'utf8');
var foundation=fs.readFileSync(path.join(root,'supabase/migrations/20260801_5_4_0_device_authorization_foundation.sql'),'utf8');
var administrationService=fs.readFileSync(path.join(root,'js/supabase/device-authorization-administration-service.js'),'utf8');
var tables=['webauthn_privileged_device_feature','device_security_credentials','device_possession_challenges','device_possession_challenge_consumers','privileged_device_listing_sessions','system_owner_credential_bootstrap_authorizations','system_owner_credential_recovery_authorizations','privileged_device_authorization_audit_log','system_owner_device_authorization_operations'];
function isolatedFunction(name){var start=migration.toLowerCase().indexOf(('create or replace function public.'+name+'()').toLowerCase());assert.ok(start>=0,name+' function missing');var end=migration.indexOf('\n$$;',start);assert.ok(end>start,name+' function terminator missing');return migration.slice(start,end+4);}
var credentialLifecycleFunction=isolatedFunction('guard_device_security_credential_lifecycle');
var deviceAuthorizationCredentialFunction=isolatedFunction('guard_device_authorization_security_credential_state');
var challengeConsumerFunction=isolatedFunction('guard_device_possession_challenge_consumer');
var bootstrapLifecycleFunction=isolatedFunction('guard_system_owner_bootstrap_authorization_lifecycle');
var recoveryLifecycleFunction=isolatedFunction('guard_system_owner_recovery_authorization_lifecycle');

tables.forEach(function(name){
  assert.match(migration,new RegExp('create table public\\.'+name+'\\s*\\(','i'),name+' table missing');
  assert.match(migration,new RegExp('alter table public\\.'+name+' enable row level security','i'),name+' RLS missing');
  assert.match(migration,new RegExp('revoke all on table public\\.'+name+' from public,anon,authenticated','i'),name+' browser revoke missing');
  assert.ok(verification.includes(name),name+' verification missing');
});

['webauthn_credential_id','user_id','device_id','credential_kind','public_key_cose','public_key_algorithm','aaguid','transports','sign_count','backup_eligible','backup_state','user_verification_policy','lifecycle_status','created_at','enrolled_at','activated_at','last_used_at','revoked_at','revoked_by','revocation_reason'].forEach(function(field){assert.ok(migration.includes(field),field);});
assert.match(migration,/webauthn_credential_id bytea not null unique/i);
assert.match(migration,/foreign key\(user_id,device_id\)[\s\S]*user_device_authorizations\(user_id,device_id\)/i);
assert.match(migration,/privileged_device_audit_actor_credential_fk[\s\S]*foreign key\(actor_credential_id,actor_user_id_snapshot,actor_device_id\)/i);
assert.match(migration,/backup_eligible=false and backup_state=false/i);
assert.match(migration,/user_verification_policy='required'/i);
assert.match(migration,/lifecycle_status in \('active','rotation_pending','recovery_required'\)[\s\S]*enrolled_at is not null[\s\S]*activated_at is not null/i);
assert.match(migration,/lifecycle_status='revoked' and revoked_at is not null/i);
assert.match(migration,/DEVICE_SECURITY_CREDENTIAL_IDENTITY_IMMUTABLE/);
assert.match(migration,/DEVICE_SECURITY_CREDENTIAL_DELETE_FORBIDDEN/);
assert.match(migration,/DEVICE_SECURITY_CREDENTIAL_TRANSITION_INVALID/);
assert.match(migration,/DEVICE_SECURITY_CREDENTIAL_COUNTER_REGRESSION/);
assert.match(migration,/DEVICE_SECURITY_CREDENTIAL_MUST_ENROLL_PENDING/);
assert.match(migration,/DEVICE_SECURITY_CREDENTIAL_DEVICE_NOT_APPROVED/);
assert.match(migration,/select authorizations\.authorization_status,authorizations\.revoked_at[\s\S]*for update/i);
assert.match(migration,/DEVICE_AUTHORIZATION_HAS_LIVE_SECURITY_CREDENTIAL/);
assert.match(migration,/user_device_authorizations_security_credential_guard/);
assert.match(migration,/old\.lifecycle_status='recovery_required'[\s\S]*new\.lifecycle_status not in \('recovery_required','revoked'\)/i);

['challenge_hash','session_id','actor_device_id','credential_id','purpose','target_user_id','target_device_id','operation_id','expected_origin','expected_rp_id','environment','expires_at','verified_at','consumed_at','failed_at','failure_code','verification_context'].forEach(function(field){assert.ok(migration.includes(field),field);});
assert.match(migration,/challenge_hash bytea not null unique/);
assert.match(migration,/octet_length\(challenge_hash\)=32/);
['SYSTEM_OWNER_PENDING_DEVICE_LIST','SYSTEM_OWNER_PENDING_DEVICE_APPROVE','SYSTEM_OWNER_PENDING_DEVICE_REJECT','SYSTEM_OWNER_DEVICE_REVOKE','SYSTEM_OWNER_DEVICE_REPLACEMENT','SYSTEM_OWNER_CREDENTIAL_ENROLLMENT','SYSTEM_OWNER_CREDENTIAL_ROTATION','SYSTEM_OWNER_CREDENTIAL_RECOVERY'].forEach(function(purpose){assert.ok(migration.includes("'"+purpose+"'"),purpose);});
assert.match(migration,/consumed_at is null or \(verified_at is not null and consumed_at>=verified_at\)/i);
assert.match(migration,/DEVICE_POSSESSION_CHALLENGE_BINDING_IMMUTABLE/);
assert.match(migration,/DEVICE_POSSESSION_CHALLENGE_TERMINAL/);
assert.match(migration,/expires_at>created_at and expires_at<=created_at\+interval '2 minutes'/i);
assert.match(migration,/DEVICE_POSSESSION_CHALLENGE_VERIFICATION_IMMUTABLE/);
assert.match(migration,/DEVICE_POSSESSION_CHALLENGE_CONSUME_REQUIRES_VERIFICATION/);
assert.match(migration,/new\.verification_context is distinct from old\.verification_context/i);
assert.match(migration,/verification_context jsonb null default null/i);
assert.match(migration,/DEVICE_POSSESSION_CHALLENGE_INITIAL_STATE_INVALID/);
assert.match(migration,/before insert or update or delete on public\.device_possession_challenges/i);
assert.match(migration,/DEVICE_POSSESSION_CHALLENGE_CONSUMER_REQUIRED/);
['challenge_hash','user_id','session_id','actor_device_id','credential_id','purpose','target_user_id','target_device_id','replaced_device_id','replacement_device_id','operation_id','expected_origin','expected_rp_id','environment','expires_at','created_at'].forEach(function(field){assert.match(migration,new RegExp('new\\.'+field+'[\\s\\S]*old\\.'+field,'i'),'immutable challenge binding missing: '+field);});

assert.match(migration,/scope text not null check \(scope='SYSTEM_OWNER_PENDING_DEVICE_LIST_READ_ONLY'\)/i);
assert.match(migration,/privileged_device_listing_sessions_challenge_fk[\s\S]*foreign key\(source_challenge_id,user_id,session_id,actor_device_id,[\s\S]*credential_id,source_challenge_purpose,environment\)/i);
assert.match(migration,/source_challenge_purpose text not null[\s\S]*SYSTEM_OWNER_PENDING_DEVICE_LIST/i);
assert.match(migration,/expires_at>issued_at and expires_at<=issued_at\+interval '5 minutes'/i);
assert.match(migration,/PRIVILEGED_LISTING_SESSION_BINDING_IMMUTABLE/);
assert.match(migration,/PRIVILEGED_LISTING_SESSION_REVOKED_TERMINAL/);
assert.match(migration,/PRIVILEGED_LISTING_SESSION_SOURCE_CHALLENGE_INVALID/);
assert.match(migration,/challenges\.verified_at is not null[\s\S]*challenges\.failed_at is null[\s\S]*challenges\.consumed_at is null[\s\S]*challenges\.expires_at>now\(\)[\s\S]*for update/i);
assert.match(migration,/privileged_device_listing_sessions_consumer_fk/);
var listingTable=migration.match(/create table public\.privileged_device_listing_sessions \([\s\S]*?\n\);/i)[0];
assert.doesNotMatch(listingTable,/(?:target_user_id|target_device_id|operation_id)/i,'listing sessions must not carry mutation targets');
assert.match(migration,/authorization_hash bytea not null unique/);
assert.match(migration,/system_owner_credential_bootstrap_device_fk/);
assert.match(migration,/issuance_audit_id uuid not null unique/);
assert.match(migration,/recovery_method in \([\s\S]*active_platform_credential[\s\S]*recovery_security_key[\s\S]*controlled_operator/i);
assert.match(migration,/not_before timestamptz not null/);
assert.match(migration,/SYSTEM_OWNER_BOOTSTRAP_CONSUMPTION_ONE_WAY/);
assert.match(migration,/SYSTEM_OWNER_BOOTSTRAP_BINDING_IMMUTABLE/);
assert.match(bootstrapLifecycleFunction,/SYSTEM_OWNER_BOOTSTRAP_INITIAL_STATE_INVALID/);
assert.match(migration,/before insert or update or delete on public\.system_owner_credential_bootstrap_authorizations/i);
assert.match(bootstrapLifecycleFunction,/tg_op='INSERT'[\s\S]*new\.consumed_at is not null[\s\S]*SYSTEM_OWNER_BOOTSTRAP_INITIAL_STATE_INVALID/i);
assert.doesNotMatch(credentialLifecycleFunction,/SYSTEM_OWNER_BOOTSTRAP_INITIAL_STATE_INVALID/);
assert.doesNotMatch(deviceAuthorizationCredentialFunction,/SYSTEM_OWNER_BOOTSTRAP_INITIAL_STATE_INVALID/);
assert.match(bootstrapLifecycleFunction,/statement_timestamp\(\)<old\.issued_at[\s\S]*statement_timestamp\(\)>old\.expires_at/i);
['historical','future','arbitrary'].forEach(function(candidate){assert.match(bootstrapLifecycleFunction,/new\.consumed_at is not null[\s\S]*SYSTEM_OWNER_BOOTSTRAP_CALLER_CONSUMED_AT_FORBIDDEN/i,'bootstrap must reject '+candidate+' caller timestamp');});
assert.match(bootstrapLifecycleFunction,/new\.consumed_at=statement_timestamp\(\)/i);
assert.match(migration,/intended_device_authorization_status='approved'/i);
assert.match(migration,/intended_user_system_owner=true/i);
assert.match(recoveryLifecycleFunction,/SYSTEM_OWNER_RECOVERY_TERMINAL/);
assert.match(recoveryLifecycleFunction,/SYSTEM_OWNER_RECOVERY_TRANSITION_INVALID/);
assert.match(recoveryLifecycleFunction,/SYSTEM_OWNER_RECOVERY_INITIAL_STATE_INVALID/);
assert.match(migration,/before insert or update or delete on public\.system_owner_credential_recovery_authorizations/i);
assert.match(recoveryLifecycleFunction,/tg_op='INSERT'[\s\S]*new\.status<>'pending_wait'[\s\S]*new\.consumed_at is not null[\s\S]*new\.not_before<=new\.issued_at[\s\S]*SYSTEM_OWNER_RECOVERY_INITIAL_STATE_INVALID/i);
assert.match(recoveryLifecycleFunction,/old\.status='pending_wait' and new\.status='ready'[\s\S]*statement_timestamp\(\)<old\.not_before[\s\S]*SYSTEM_OWNER_RECOVERY_WAITING_PERIOD_ACTIVE/i);
assert.match(recoveryLifecycleFunction,/statement_timestamp\(\)>old\.expires_at[\s\S]*SYSTEM_OWNER_RECOVERY_CONSUMPTION_OUTSIDE_WINDOW/i);
['historical','future','arbitrary'].forEach(function(candidate){assert.match(recoveryLifecycleFunction,/old\.status='ready' and new\.status='consumed'[\s\S]*new\.consumed_at is not null[\s\S]*SYSTEM_OWNER_RECOVERY_CALLER_CONSUMED_AT_FORBIDDEN/i,'recovery must reject '+candidate+' caller timestamp');});
assert.match(recoveryLifecycleFunction,/new\.consumed_at=statement_timestamp\(\)/i);
assert.match(migration,/new\.not_before<>old\.not_before[\s\S]*new\.expires_at<>old\.expires_at/i);
var recoveryTable=migration.match(/create table public\.system_owner_credential_recovery_authorizations \([\s\S]*?\n\);/i)[0];
assert.match(recoveryTable,/environment text not null[\s\S]*local[\s\S]*development_preview[\s\S]*production/i);
assert.match(migration,/new\.environment<>old\.environment/i);

var consumerTable=migration.match(/create table public\.device_possession_challenge_consumers \([\s\S]*?\n\);/i)[0];
['credential_enrollment','credential_rotation','credential_recovery','listing_session','device_authorization_operation'].forEach(function(kind){assert.ok(consumerTable.includes("'"+kind+"'"),kind+' consumer missing');});
assert.match(consumerTable,/challenge_id uuid primary key/i);
['user_id','session_id','actor_device_id','actor_credential_id','environment'].forEach(function(field){assert.ok(consumerTable.includes(field),field+' consumer context missing');});
assert.match(consumerTable,/device_possession_challenge_consumers_challenge_actor_fk[\s\S]*challenge_id,user_id,session_id,actor_device_id,[\s\S]*challenge_purpose,environment/i);
assert.match(consumerTable,/device_possession_challenge_consumers_challenge_credential_fk[\s\S]*challenge_id,actor_credential_id/i);
assert.match(migration,/DEVICE_POSSESSION_CHALLENGE_NOT_CONSUMABLE/);
assert.match(migration,/device_possession_challenge_consumers_guard/);
assert.match(challengeConsumerFunction,/tg_op<>'INSERT'[\s\S]*DEVICE_POSSESSION_CHALLENGE_CONSUMER_IMMUTABLE/i);
assert.match(challengeConsumerFunction,/challenges\.user_id=new\.user_id[\s\S]*challenges\.session_id=new\.session_id[\s\S]*challenges\.actor_device_id=new\.actor_device_id[\s\S]*challenges\.credential_id is not distinct from new\.actor_credential_id[\s\S]*challenges\.environment=new\.environment/i);
assert.match(challengeConsumerFunction,/where challenges\.id=new\.challenge_id[\s\S]*challenges\.purpose=new\.challenge_purpose[\s\S]*for update/i);
assert.match(challengeConsumerFunction,/challenge_row\.verified_at is null[\s\S]*challenge_row\.failed_at is not null[\s\S]*challenge_row\.consumed_at is not null[\s\S]*challenge_row\.expires_at<=now\(\)/i);

['actor_user_id','actor_device_id','actor_credential_id','session_id_hash','challenge_id','target_user_id','target_device_id','action','operation_id','result','origin','rp_id','user_verified','backup_eligible','backup_state','created_at','security_context'].forEach(function(field){assert.ok(migration.includes(field),field);});
assert.match(migration,/privileged_device_authorization_audit_immutable/);
assert.match(migration,/prevent_device_authorization_audit_mutation/);
assert.match(migration,/actor_credential_id[\s\S]*challenge_id[\s\S]*user_verified=true[\s\S]*backup_eligible=false[\s\S]*backup_state=false/i);
assert.match(migration,/replaced_device_id uuid null/);
assert.match(migration,/replacement_device_id uuid null/);
assert.match(migration,/system_owner_device_operations_challenge_actor_fk[\s\S]*foreign key\(challenge_id,actor_user_id_snapshot,session_id,actor_device_id,[\s\S]*actor_credential_id,challenge_purpose,environment,operation_id\)/i);
assert.match(migration,/system_owner_device_operations_challenge_target_fk[\s\S]*foreign key\(challenge_id,target_user_id_snapshot,target_device_id\)/i);
assert.match(migration,/system_owner_device_operations_challenge_replacement_fk[\s\S]*foreign key\(challenge_id,target_user_id_snapshot,replaced_device_id,replacement_device_id\)/i);
assert.match(migration,/system_owner_device_operations_action_purpose[\s\S]*SYSTEM_OWNER_PENDING_DEVICE_APPROVE[\s\S]*SYSTEM_OWNER_PENDING_DEVICE_REJECT[\s\S]*SYSTEM_OWNER_DEVICE_REVOKE[\s\S]*SYSTEM_OWNER_DEVICE_REPLACEMENT/i);
assert.match(migration,/system_owner_device_authorization_operations_immutable/);
var operationTable=migration.match(/create table public\.system_owner_device_authorization_operations \([\s\S]*?\n\);/i)[0];
assert.match(operationTable,/environment text not null[\s\S]*local[\s\S]*development_preview[\s\S]*production/i);
assert.match(operationTable,/system_owner_device_operations_challenge_actor_fk[\s\S]*foreign key\([\s\S]*challenge_purpose,environment,operation_id\)[\s\S]*purpose,environment,operation_id\)/i);
assert.match(operationTable,/system_owner_device_operations_consumer_fk[\s\S]*actor_user_id_snapshot,session_id,actor_device_id,[\s\S]*actor_credential_id,challenge_purpose,environment,operation_id,consumer_kind/i);
var auditTable=migration.match(/create table public\.privileged_device_authorization_audit_log \([\s\S]*?\n\);/i)[0];
var auditActionPurpose=(auditTable.match(/constraint privileged_device_audit_action_purpose[\s\S]*?\n\s*\),\n\s*constraint privileged_device_audit_live_snapshot_consistency/i)||[])[0];
assert.ok(auditActionPurpose,'isolated audit action-purpose constraint missing');
['session_id','challenge_purpose','environment','challenge_target_user_id','challenge_target_device_id','replaced_device_id','replacement_device_id'].forEach(function(field){assert.ok(auditTable.includes(field),field+' audit context missing');});
assert.match(auditTable,/privileged_device_audit_challenge_actor_fk[\s\S]*session_id[\s\S]*challenge_purpose,environment/i);
assert.match(auditTable,/privileged_device_audit_challenge_operation_fk/);
assert.match(auditTable,/privileged_device_audit_challenge_target_fk/);
assert.match(auditTable,/privileged_device_audit_challenge_replacement_fk/);
assert.match(auditTable,/privileged_device_audit_action_purpose[\s\S]*SYSTEM_OWNER_PENDING_DEVICE_APPROVE[\s\S]*SYSTEM_OWNER_PENDING_DEVICE_REJECT[\s\S]*SYSTEM_OWNER_DEVICE_REPLACEMENT/i);
assert.match(auditActionPurpose,/action='credential_enrolled'[\s\S]*challenge_purpose='SYSTEM_OWNER_CREDENTIAL_ENROLLMENT'[\s\S]*challenge_target_user_id is null[\s\S]*challenge_target_device_id is null[\s\S]*target_user_id_snapshot=actor_user_id_snapshot[\s\S]*target_device_id=actor_device_id/i);
assert.match(auditActionPurpose,/action='credential_activated'[\s\S]*SYSTEM_OWNER_CREDENTIAL_ROTATION[\s\S]*SYSTEM_OWNER_CREDENTIAL_RECOVERY[\s\S]*challenge_target_user_id is not null[\s\S]*challenge_target_device_id is not null[\s\S]*challenge_target_user_id=target_user_id_snapshot[\s\S]*challenge_target_device_id=target_device_id/i);
assert.match(auditActionPurpose,/action='credential_revoked'[\s\S]*SYSTEM_OWNER_CREDENTIAL_ROTATION[\s\S]*SYSTEM_OWNER_CREDENTIAL_RECOVERY[\s\S]*challenge_target_user_id is not null[\s\S]*challenge_target_device_id is not null[\s\S]*challenge_target_user_id=target_user_id_snapshot[\s\S]*challenge_target_device_id=target_device_id/i);
['pending_device_approved','pending_device_rejected','device_revoked'].forEach(function(action){var branch=auditActionPurpose.slice(auditActionPurpose.indexOf("action='"+action+"'"));assert.match(branch,/challenge_target_user_id is not null[\s\S]*challenge_target_device_id is not null[\s\S]*challenge_target_user_id=target_user_id_snapshot[\s\S]*challenge_target_device_id=target_device_id/i,action+' nullable target bypass');});
assert.doesNotMatch(auditTable,/action in \('credential_enrolled','credential_activated','credential_revoked'\)[\s\S]*challenge_purpose in/i,'credential actions must not share an arbitrary purpose group');
assert.match(migration,/privileged_device_audit_live_snapshot_consistency[\s\S]*actor_user_id=actor_user_id_snapshot[\s\S]*target_user_id=target_user_id_snapshot/i);
assert.match(migration,/system_owner_device_operations_live_snapshot_consistency[\s\S]*actor_user_id=actor_user_id_snapshot[\s\S]*target_user_id=target_user_id_snapshot/i);

assert.match(migration,/enabled boolean not null default false check \(enabled=false\)/i);
assert.match(migration,/values\(1,false\)/i);
assert.match(migration,/WEBAUTHN_PHASE_A_FEATURE_MUST_BE_DISABLED/);
assert.doesNotMatch(migration,/create or replace function public\.(?:list_system_owner_pending_device_authorizations|approve_system_owner_pending_device|reject_system_owner_pending_device)/i);
assert.doesNotMatch(migration,/grant execute[\s\S]*to authenticated/i,'Phase A must grant no RPC execute to authenticated');
assert.doesNotMatch(migration,/navigator\.credentials|supabase\/functions|webauthn.*verify/i);
assert.match(migration,/alter table public\.%I owner to %I/i);
assert.match(migration,/alter function public\.%s owner to %I/i);
assert.match(migration,/WEBAUTHN_PHASE_A_RELATION_OWNER_INVALID/);
assert.match(migration,/WEBAUTHN_PHASE_A_POLICY_FORBIDDEN/);
assert.match(migration,/aclexplode\(coalesce\(classes\.relacl,[\s\S]*acldefault\('r',classes\.relowner\)[\s\S]*privileges\.grantee=0/i);
assert.match(migration,/aclexplode\(coalesce\(procedures\.proacl,[\s\S]*acldefault\('f',procedures\.proowner\)[\s\S]*privileges\.grantee=0/i);
assert.doesNotMatch(migration,/has_(?:table|function)_privilege\('public'/i);
['guard_device_security_credential_lifecycle','guard_device_authorization_security_credential_state','guard_device_possession_challenge_identity','guard_device_possession_challenge_consumer','guard_privileged_device_listing_session_lifecycle','guard_system_owner_bootstrap_authorization_lifecycle','guard_system_owner_recovery_authorization_lifecycle'].forEach(function(name){assert.match(migration,new RegExp('security definer[\\s\\S]*set search_path=pg_catalog, public[\\s\\S]*revoke all on function public\\.'+name+'\\(\\) from public,anon,authenticated','i'),name+' ownership/grant contract missing');});

['no_phase_a_policies','controlled_relation_owner','controlled_function_owner','helper_security_definer_and_search_path_valid','browser_helper_execute_denied','challenge_max_two_minutes','listing_exact_assertion_binding','challenge_initial_state_enforced','challenge_lifecycle_semantics','listing_verified_unexpired_source_enforced','recovery_environment_immutable','credential_activation_locked_and_revalidated','operation_environment_exactly_bound','universal_challenge_consumer_binding','live_snapshot_consistency','audit_exact_challenge_context','feature_enable_structurally_impossible','operation_exact_challenge_binding','operation_action_purpose_binding','bootstrap_lifecycle_guard','recovery_lifecycle_guard','bootstrap_insert_issued_state_enforced','bootstrap_current_time_consumption','recovery_insert_pending_wait_enforced','recovery_wait_and_current_time_consumption','uuid_only_global_rpcs_absent'].forEach(function(invariant){assert.ok(verification.includes(invariant),'verification missing '+invariant);});
assert.match(verification,/pg_get_functiondef/i);
assert.match(verification,/pg_get_triggerdef/i);
assert.match(verification,/device_possession_challenges_expiration[\s\S]*00:02:00[\s\S]*::interval/i);
assert.match(verification,/privileged_device_listing_sessions_expiration[\s\S]*00:05:00[\s\S]*::interval/i);
assert.match(verification,/pg_constraint[\s\S]*conkey[\s\S]*confkey[\s\S]*pg_attribute/i);
assert.match(verification,/local_columns=array\[[\s\S]*referenced_columns=array\[/i);
assert.match(verification,/tgname='device_possession_challenge_consumers_guard'[\s\S]*table_name='device_possession_challenge_consumers'[\s\S]*function_name='guard_device_possession_challenge_consumer'/i);
assert.match(verification,/universal_challenge_consumer_binding[\s\S]*|definition ilike '%verified_at is null%'/i);
assert.match(verification,/system_owner_device_operations_challenge_actor_fk[\s\S]*local_columns=array\['challenge_id','actor_user_id_snapshot','session_id','actor_device_id','actor_credential_id','challenge_purpose','environment','operation_id'\]::name\[\][\s\S]*referenced_columns=array\['id','user_id','session_id','actor_device_id','credential_id','purpose','environment','operation_id'\]::name\[\]/i);
assert.match(verification,/privileged_device_audit_action_purpose[\s\S]*definition ilike '%credential_enrolled%SYSTEM_OWNER_CREDENTIAL_ENROLLMENT%/i);
assert.match(verification,/privileged_device_authorization_audit_immutable'[\s\S]*before delete or update[\s\S]*prevent_device_authorization_audit_mutation/i);
assert.match(verification,/authorization_initial_columns/i);
assert.match(verification,/privileges\.grantee=0/i);
assert.doesNotMatch(verification,/has_(?:table|function)_privilege\('public'/i);
assert.ok(verification.includes('Future Phase B/D transaction tests must exercise concurrent activation/revocation and atomic challenge consumption.'),'future runtime coverage classification missing');
assert.match(administrationService,/WEBAUTHN_PRIVILEGED_DEVICE_PHASE_A_ENABLED=false/);
assert.doesNotMatch(administrationService,/\.rpc\('(?:list_system_owner_pending_device_authorizations|approve_system_owner_pending_device|reject_system_owner_pending_device)'/i,'stale UUID-only client RPC must be unreachable and absent');

['require_device_authorization_manager','list_member_device_authorizations','approve_member_device','reject_member_pending_device','revoke_member_device','replace_member_active_device'].forEach(function(name){assert.ok(organizationMigration.includes('public.'+name+'('),name+' historical organization path missing');assert.ok(!migration.includes('create or replace function public.'+name+'('),name+' must remain untouched');});
['register_or_refresh_current_device','request_current_device_authorization','require_current_approved_device'].forEach(function(name){assert.ok(foundation.includes('public.'+name+'('),name+' historical foundation missing');assert.ok(!migration.includes('create or replace function public.'+name+'('),name+' must remain untouched');});
assert.doesNotMatch(verification,/^\s*(?:insert|update|delete|create|alter|drop|grant|revoke|truncate)\b/im);

console.log('WebAuthn privileged device Phase A foundation tests: passed (inert schema, restrictive grants, disabled feature, existing boundaries preserved)');
