-- Phase W1: one allowlisted Platform device-operation dispatcher for Conference and Warehouse.

do $$ declare signature text; begin
  perform 'platform.execute_conference_device_operation_phase1c_core(uuid,uuid,bytea,text,jsonb)'::regprocedure;
  foreach signature in array array[
    'warehouse.list_stores(uuid,uuid)','warehouse.list_item_master(uuid)','warehouse.view_stock(uuid,uuid)','warehouse.discover_stores(uuid,boolean)','warehouse.list_documents(uuid,text,uuid,text,timestamptz,uuid,integer)','warehouse.get_document(uuid,uuid)','warehouse.list_approval_queue(uuid,timestamptz,uuid,integer)','warehouse.list_reversal_requests(uuid,text,timestamptz,uuid,integer)','warehouse.list_history(uuid,uuid,uuid,uuid,text,timestamptz,timestamptz,bigint,integer)','warehouse.list_balances(uuid,uuid,uuid,integer)',
    'warehouse.create_store(uuid,uuid,text,text,text,text)','warehouse.update_store(uuid,uuid,uuid,bigint,text,text,text,text,text)','warehouse.upsert_item_master(uuid,uuid,text,uuid,bigint,jsonb)','warehouse.create_receipt_draft(uuid,uuid,jsonb)','warehouse.create_issue_draft(uuid,uuid,jsonb)','warehouse.create_transfer_draft(uuid,uuid,jsonb)','warehouse.create_adjustment_draft(uuid,uuid,text,jsonb)','warehouse.update_document_draft(uuid,uuid,text,uuid,bigint,jsonb)','warehouse.submit_adjustment_for_approval(uuid,uuid,uuid,bigint)','warehouse.decide_adjustment_approval(uuid,uuid,uuid,bigint,text,text)','warehouse.post_receipt(uuid,uuid,uuid,bigint)','warehouse.post_issue(uuid,uuid,uuid,bigint)','warehouse.post_transfer(uuid,uuid,uuid,bigint)','warehouse.post_adjustment(uuid,uuid,uuid,bigint)','warehouse.create_reversal_request(uuid,uuid,uuid,text)','warehouse.submit_reversal_request(uuid,uuid,uuid,bigint,text)','warehouse.decide_reversal_approval(uuid,uuid,uuid,bigint,text,text)','warehouse.post_reversal(uuid,uuid,uuid,bigint)','warehouse.authorize_report_export(uuid,uuid)','warehouse.stage_import(uuid,uuid,jsonb)'
  ] loop perform signature::regprocedure; end loop;
end $$;

create or replace function platform.execute_device_operation(
  p_user_id uuid,p_session_id uuid,p_token_hash bytea,p_module text,p_operation text,p_args jsonb
) returns jsonb language plpgsql security definer
set search_path=pg_catalog,public,platform,platform_private,warehouse,warehouse_private as $$
declare session platform_private.device_sessions%rowtype; result jsonb;
begin
  if coalesce(auth.jwt()->>'role','') <> 'service_role' then raise exception 'PLATFORM_OPERATION_BACKEND_REQUIRED' using errcode='42501'; end if;
  if p_user_id is null or p_session_id is null or octet_length(p_token_hash)<>32 or p_module not in ('conference','warehouse')
    or p_args is null or jsonb_typeof(p_args)<>'object' then raise exception 'PLATFORM_OPERATION_ARGUMENT_INVALID' using errcode='22023'; end if;
  if p_args ? 'p_actor_device_id' or (p_module='warehouse' and p_args ? 'p_device_id') then raise exception 'ACTOR_DEVICE_OVERRIDE_DENIED' using errcode='22023'; end if;
  select item.* into session from platform_private.device_sessions item
  join platform.device_key_bindings binding on binding.id=item.binding_id
  join platform.user_device_authorizations uda on uda.id=item.device_authorization_id
  join platform.devices device on device.id=item.device_id join platform.profiles profile on profile.user_id=item.user_id
  where item.id=p_session_id and item.user_id=p_user_id and item.token_hash=p_token_hash
    and item.purpose='PLATFORM_DEVICE_SESSION' and item.revoked_at is null and item.expires_at>statement_timestamp()
    and binding.user_id=item.user_id and binding.device_id=item.device_id and binding.device_authorization_id=item.device_authorization_id
    and binding.public_key_thumbprint=item.public_key_thumbprint and binding.algorithm='ECDSA_P256_SHA256'
    and binding.lifecycle_status='active' and binding.revoked_at is null and binding.retired_at is null
    and uda.user_id=item.user_id and uda.device_id=item.device_id and uda.status='approved' and uda.revoked_at is null
    and device.lifecycle_status='active' and device.retired_at is null and device.compromised_at is null and profile.account_status='approved';
  if not found then raise exception 'DEVICE_SESSION_INVALID' using errcode='42501'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',p_user_id,'role','service_role')::text,true);
  perform set_config('platform.phase1c_context',jsonb_build_object('purpose','PLATFORM_DEVICE_SESSION_DISPATCH','session_id',session.id,'user_id',session.user_id,'device_id',session.device_id,'authorization_id',session.device_authorization_id,'binding_id',session.binding_id,'token_hash',encode(p_token_hash,'hex'))::text,true);
  if p_module='conference' then
    return platform.execute_conference_device_operation_phase1c_core(p_user_id,p_session_id,p_token_hash,p_operation,p_args);
  end if;
  case p_operation
  when 'list_stores' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_store_id']); select coalesce(jsonb_agg(to_jsonb(x)),'[]') into result from warehouse.list_stores(session.device_id,(p_args->>'p_store_id')::uuid) x;
  when 'list_item_master' then perform platform_private.require_exact_jsonb_keys(p_args,'{}'); result:=warehouse.list_item_master(session.device_id);
  when 'view_stock' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_store_id']); result:=warehouse.view_stock(session.device_id,(p_args->>'p_store_id')::uuid);
  when 'discover_stores' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_include_inactive']); result:=warehouse.discover_stores(session.device_id,(p_args->>'p_include_inactive')::boolean);
  when 'list_documents' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_document_kind','p_store_id','p_status','p_before_created_at','p_before_id','p_limit']); result:=warehouse.list_documents(session.device_id,p_args->>'p_document_kind',(p_args->>'p_store_id')::uuid,p_args->>'p_status',(p_args->>'p_before_created_at')::timestamptz,(p_args->>'p_before_id')::uuid,(p_args->>'p_limit')::integer);
  when 'get_document' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_document_id']); result:=warehouse.get_document(session.device_id,(p_args->>'p_document_id')::uuid);
  when 'list_approval_queue' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_before_created_at','p_before_id','p_limit']); result:=warehouse.list_approval_queue(session.device_id,(p_args->>'p_before_created_at')::timestamptz,(p_args->>'p_before_id')::uuid,(p_args->>'p_limit')::integer);
  when 'list_reversal_requests' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_status','p_before_created_at','p_before_id','p_limit']); result:=warehouse.list_reversal_requests(session.device_id,p_args->>'p_status',(p_args->>'p_before_created_at')::timestamptz,(p_args->>'p_before_id')::uuid,(p_args->>'p_limit')::integer);
  when 'list_history' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_store_id','p_document_id','p_item_id','p_document_kind','p_from','p_to','p_before_sequence','p_limit']); result:=warehouse.list_history(session.device_id,(p_args->>'p_store_id')::uuid,(p_args->>'p_document_id')::uuid,(p_args->>'p_item_id')::uuid,p_args->>'p_document_kind',(p_args->>'p_from')::timestamptz,(p_args->>'p_to')::timestamptz,(p_args->>'p_before_sequence')::bigint,(p_args->>'p_limit')::integer);
  when 'list_balances' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_store_id','p_before_item_id','p_limit']); result:=warehouse.list_balances(session.device_id,(p_args->>'p_store_id')::uuid,(p_args->>'p_before_item_id')::uuid,(p_args->>'p_limit')::integer);
  when 'create_store' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_name','p_type','p_address','p_notes']); result:=warehouse.create_store(session.device_id,(p_args->>'p_operation_id')::uuid,p_args->>'p_name',p_args->>'p_type',p_args->>'p_address',p_args->>'p_notes');
  when 'update_store' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_store_id','p_expected_revision','p_name','p_type','p_address','p_status','p_notes']); result:=warehouse.update_store(session.device_id,(p_args->>'p_operation_id')::uuid,(p_args->>'p_store_id')::uuid,(p_args->>'p_expected_revision')::bigint,p_args->>'p_name',p_args->>'p_type',p_args->>'p_address',p_args->>'p_status',p_args->>'p_notes');
  when 'upsert_item_master' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_entity_kind','p_entity_id','p_expected_revision','p_payload']); result:=warehouse.upsert_item_master(session.device_id,(p_args->>'p_operation_id')::uuid,p_args->>'p_entity_kind',(p_args->>'p_entity_id')::uuid,(p_args->>'p_expected_revision')::bigint,p_args->'p_payload');
  when 'create_receipt_draft','create_issue_draft','create_transfer_draft' then
    perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_payload']);
    if p_operation='create_receipt_draft' then result:=warehouse.create_receipt_draft(session.device_id,(p_args->>'p_operation_id')::uuid,p_args->'p_payload'); elsif p_operation='create_issue_draft' then result:=warehouse.create_issue_draft(session.device_id,(p_args->>'p_operation_id')::uuid,p_args->'p_payload'); else result:=warehouse.create_transfer_draft(session.device_id,(p_args->>'p_operation_id')::uuid,p_args->'p_payload'); end if;
  when 'create_adjustment_draft' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_adjustment_kind','p_payload']); result:=warehouse.create_adjustment_draft(session.device_id,(p_args->>'p_operation_id')::uuid,p_args->>'p_adjustment_kind',p_args->'p_payload');
  when 'update_document_draft' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_document_kind','p_document_id','p_expected_revision','p_payload']); result:=warehouse.update_document_draft(session.device_id,(p_args->>'p_operation_id')::uuid,p_args->>'p_document_kind',(p_args->>'p_document_id')::uuid,(p_args->>'p_expected_revision')::bigint,p_args->'p_payload');
  when 'submit_adjustment_for_approval','post_receipt','post_issue','post_transfer','post_adjustment' then
    perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_document_id','p_expected_revision']);
    if p_operation='submit_adjustment_for_approval' then result:=warehouse.submit_adjustment_for_approval(session.device_id,(p_args->>'p_operation_id')::uuid,(p_args->>'p_document_id')::uuid,(p_args->>'p_expected_revision')::bigint); elsif p_operation='post_receipt' then result:=warehouse.post_receipt(session.device_id,(p_args->>'p_operation_id')::uuid,(p_args->>'p_document_id')::uuid,(p_args->>'p_expected_revision')::bigint); elsif p_operation='post_issue' then result:=warehouse.post_issue(session.device_id,(p_args->>'p_operation_id')::uuid,(p_args->>'p_document_id')::uuid,(p_args->>'p_expected_revision')::bigint); elsif p_operation='post_transfer' then result:=warehouse.post_transfer(session.device_id,(p_args->>'p_operation_id')::uuid,(p_args->>'p_document_id')::uuid,(p_args->>'p_expected_revision')::bigint); else result:=warehouse.post_adjustment(session.device_id,(p_args->>'p_operation_id')::uuid,(p_args->>'p_document_id')::uuid,(p_args->>'p_expected_revision')::bigint); end if;
  when 'decide_adjustment_approval' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_document_id','p_expected_revision','p_decision','p_reason']); result:=warehouse.decide_adjustment_approval(session.device_id,(p_args->>'p_operation_id')::uuid,(p_args->>'p_document_id')::uuid,(p_args->>'p_expected_revision')::bigint,p_args->>'p_decision',p_args->>'p_reason');
  when 'create_reversal_request' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_original_document_id','p_reason']); result:=warehouse.create_reversal_request(session.device_id,(p_args->>'p_operation_id')::uuid,(p_args->>'p_original_document_id')::uuid,p_args->>'p_reason');
  when 'submit_reversal_request' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_request_id','p_expected_revision','p_reason']); result:=warehouse.submit_reversal_request(session.device_id,(p_args->>'p_operation_id')::uuid,(p_args->>'p_request_id')::uuid,(p_args->>'p_expected_revision')::bigint,p_args->>'p_reason');
  when 'decide_reversal_approval' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_request_id','p_expected_revision','p_decision','p_reason']); result:=warehouse.decide_reversal_approval(session.device_id,(p_args->>'p_operation_id')::uuid,(p_args->>'p_request_id')::uuid,(p_args->>'p_expected_revision')::bigint,p_args->>'p_decision',p_args->>'p_reason');
  when 'post_reversal' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_operation_id','p_request_id','p_expected_revision']); result:=warehouse.post_reversal(session.device_id,(p_args->>'p_operation_id')::uuid,(p_args->>'p_request_id')::uuid,(p_args->>'p_expected_revision')::bigint);
  when 'authorize_report_export' then perform platform_private.require_exact_jsonb_keys(p_args,array['p_store_id']); result:=warehouse.authorize_report_export(session.device_id,(p_args->>'p_store_id')::uuid);
  else raise exception 'WAREHOUSE_OPERATION_NOT_ALLOWED' using errcode='42501';
  end case;
  return result;
end; $$;

revoke all on function platform.execute_device_operation(uuid,uuid,bytea,text,text,jsonb) from public,anon,authenticated,service_role;
grant execute on function platform.execute_device_operation(uuid,uuid,bytea,text,text,jsonb) to service_role;

create or replace function platform.execute_conference_device_operation(p_user_id uuid,p_session_id uuid,p_token_hash bytea,p_operation text,p_args jsonb)
returns jsonb language sql security definer set search_path='' as $$
  select platform.execute_device_operation(p_user_id,p_session_id,p_token_hash,'conference',p_operation,p_args);
$$;
revoke all on function platform.execute_conference_device_operation(uuid,uuid,bytea,text,jsonb) from public,anon,authenticated,service_role;
grant execute on function platform.execute_conference_device_operation(uuid,uuid,bytea,text,jsonb) to service_role;

do $$ declare signature text; begin
  foreach signature in array array[
    'warehouse.list_stores(uuid,uuid)','warehouse.list_item_master(uuid)','warehouse.view_stock(uuid,uuid)','warehouse.discover_stores(uuid,boolean)','warehouse.list_documents(uuid,text,uuid,text,timestamptz,uuid,integer)','warehouse.get_document(uuid,uuid)','warehouse.list_approval_queue(uuid,timestamptz,uuid,integer)','warehouse.list_reversal_requests(uuid,text,timestamptz,uuid,integer)','warehouse.list_history(uuid,uuid,uuid,uuid,text,timestamptz,timestamptz,bigint,integer)','warehouse.list_balances(uuid,uuid,uuid,integer)','warehouse.create_store(uuid,uuid,text,text,text,text)','warehouse.update_store(uuid,uuid,uuid,bigint,text,text,text,text,text)','warehouse.upsert_item_master(uuid,uuid,text,uuid,bigint,jsonb)','warehouse.create_receipt_draft(uuid,uuid,jsonb)','warehouse.create_issue_draft(uuid,uuid,jsonb)','warehouse.create_transfer_draft(uuid,uuid,jsonb)','warehouse.create_adjustment_draft(uuid,uuid,text,jsonb)','warehouse.update_document_draft(uuid,uuid,text,uuid,bigint,jsonb)','warehouse.submit_adjustment_for_approval(uuid,uuid,uuid,bigint)','warehouse.decide_adjustment_approval(uuid,uuid,uuid,bigint,text,text)','warehouse.post_receipt(uuid,uuid,uuid,bigint)','warehouse.post_issue(uuid,uuid,uuid,bigint)','warehouse.post_transfer(uuid,uuid,uuid,bigint)','warehouse.post_adjustment(uuid,uuid,uuid,bigint)','warehouse.create_reversal_request(uuid,uuid,uuid,text)','warehouse.submit_reversal_request(uuid,uuid,uuid,bigint,text)','warehouse.decide_reversal_approval(uuid,uuid,uuid,bigint,text,text)','warehouse.post_reversal(uuid,uuid,uuid,bigint)','warehouse.authorize_report_export(uuid,uuid)','warehouse.stage_import(uuid,uuid,jsonb)'
  ] loop execute format('revoke execute on function %s from public,anon,authenticated',signature::regprocedure); end loop;
  foreach signature in array array[
    'warehouse.list_stores(uuid,uuid)','warehouse.list_item_master(uuid)','warehouse.view_stock(uuid,uuid)','warehouse.discover_stores(uuid,boolean)','warehouse.list_documents(uuid,text,uuid,text,timestamptz,uuid,integer)','warehouse.get_document(uuid,uuid)','warehouse.list_approval_queue(uuid,timestamptz,uuid,integer)','warehouse.list_reversal_requests(uuid,text,timestamptz,uuid,integer)','warehouse.list_history(uuid,uuid,uuid,uuid,text,timestamptz,timestamptz,bigint,integer)','warehouse.list_balances(uuid,uuid,uuid,integer)','warehouse.create_store(uuid,uuid,text,text,text,text)','warehouse.update_store(uuid,uuid,uuid,bigint,text,text,text,text,text)','warehouse.upsert_item_master(uuid,uuid,text,uuid,bigint,jsonb)','warehouse.create_receipt_draft(uuid,uuid,jsonb)','warehouse.create_issue_draft(uuid,uuid,jsonb)','warehouse.create_transfer_draft(uuid,uuid,jsonb)','warehouse.create_adjustment_draft(uuid,uuid,text,jsonb)','warehouse.update_document_draft(uuid,uuid,text,uuid,bigint,jsonb)','warehouse.submit_adjustment_for_approval(uuid,uuid,uuid,bigint)','warehouse.decide_adjustment_approval(uuid,uuid,uuid,bigint,text,text)','warehouse.post_receipt(uuid,uuid,uuid,bigint)','warehouse.post_issue(uuid,uuid,uuid,bigint)','warehouse.post_transfer(uuid,uuid,uuid,bigint)','warehouse.post_adjustment(uuid,uuid,uuid,bigint)','warehouse.create_reversal_request(uuid,uuid,uuid,text)','warehouse.submit_reversal_request(uuid,uuid,uuid,bigint,text)','warehouse.decide_reversal_approval(uuid,uuid,uuid,bigint,text,text)','warehouse.post_reversal(uuid,uuid,uuid,bigint)','warehouse.authorize_report_export(uuid,uuid)'
  ] loop execute format('grant execute on function %s to service_role',signature::regprocedure); end loop;
end $$;
