(function(global){
  'use strict';
  var routes=['stores','documents','items','stock','approvals'],labels={stores:'المخازن',documents:'المستندات',items:'الأصناف',stock:'الأرصدة',approvals:'طلبات الاعتماد'};
  function escape(value){return String(value==null?'':value).replace(/[&<>"']/g,function(char){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char];});}
  function route(){var value=global.ApplicationRouting.getLogicalPathname().split('/')[2]||'stores';return routes.indexOf(value)>=0?value:'stores';}
  function operation(value){return value==='stores'?'discover_stores':value==='items'?'list_item_master':value==='approvals'?'list_approval_queue':value==='documents'?'list_documents':'discover_stores';}
  function args(name){if(name==='discover_stores')return {p_include_inactive:true};if(name==='list_item_master')return {};if(name==='list_documents')return {p_document_kind:null,p_store_id:null,p_status:null,p_before_created_at:null,p_before_id:null,p_limit:50};if(name==='list_approval_queue')return {p_before_created_at:null,p_before_id:null,p_limit:50};return {};}
  function rows(value,data){if(value==='items')return [].concat(data&&data.categories||[],data&&data.units||[],data&&data.items||[]);return Array.isArray(data)?data:[];}
  function render(value,data,error){var node=global.document.getElementById('warehouseWorkspace');if(!node)return;var nav=routes.map(function(item){return '<button class="btn '+(item===value?'btn-blue':'btn-gray')+'" data-warehouse-route="'+item+'">'+labels[item]+'</button>';}).join('');var records=rows(value,data),content=error?'<div class="sync-settings-message">'+escape(error)+'</div>':records.length?'<div class="startup-conference-list">'+records.map(function(item){return '<div class="startup-conference-item"><strong>'+escape(item.name||item.document_number||item.code||item.id||'—')+'</strong><small>'+escape(item.status||item.store_type||item.entity_kind||'')+'</small></div>';}).join('')+'</div>':'<div class="sync-settings-message">لا توجد بيانات متاحة.</div>';node.innerHTML='<div class="conference-workspace-heading"><span>الوحدة المتاحة</span><h2>إدارة المخازن</h2></div><div class="sync-settings-actions">'+nav+'</div><section class="startup-overview"><div class="startup-actions-panel"><h3>'+labels[value]+'</h3>'+content+'</div></section>';Array.prototype.forEach.call(node.querySelectorAll('[data-warehouse-route]'),function(button){button.onclick=function(){var next='/warehouse/'+button.getAttribute('data-warehouse-route');global.history.pushState(null,'',global.ApplicationRouting.resolveLogicalRoute(next));load(button.getAttribute('data-warehouse-route'));};});}
  function load(value){value=value||route();var name=operation(value);render(value,null,null);return global.WarehouseTransport.invoke(name,args(name)).then(function(data){render(value,data,null);return data;}).catch(function(error){render(value,null,String(error&&error.code||error&&error.message||'WAREHOUSE_ACCESS_DENIED'));});}
  function open(options){var startup=global.document.getElementById('startup-dashboard'),conference=global.document.getElementById('conferenceWorkspace'),node=global.document.getElementById('warehouseWorkspace');if(startup)startup.style.display='block';if(conference)conference.style.display='none';if(node)node.style.display='block';return load(options&&options.route&&options.route.split('/')[2]);}
  global.openWarehouseWorkspace=open;
})(window);
